import { machines } from '../src/data.ts'
import { writeFileSync } from 'node:fs'

const q = v => v === undefined || v === null ? 'null' : `'${String(v).replace(/'/g, "''")}'`
const n = v => v === undefined || v === null ? 'null' : Number(v)
const arr = a => `array[${(a || []).map(q).join(',')}]::text[]`

const rows = machines.map(m => `(${[
  n(m.lot), n(m.year), q(m.make), q(m.model), q(m.title), q(m.category), q(m.power),
  n(m.hours), q(m.serial), q(m.location), q(m.imageUrl), q(m.sourceUrl), arr(m.features),
  q(m.notes), q(m.priority), n(m.fleetFit), n(m.partsSupport), n(m.rentalDemand),
  m.sourceVerified ? 'true' : 'false',
].join(', ')})`).join(',\n  ')

const sql = `-- Generated by scripts/gen-seed.mjs. Do not edit by hand.
insert into ehs.machines (
  lot, year, make, model, title, category, power, hours, serial, location,
  image_url, source_url, features, notes, priority, fleet_fit, parts_support,
  rental_demand, source_verified
) values
  ${rows}
on conflict (lot) do nothing;

insert into ehs.machine_states (lot)
select lot from ehs.machines
on conflict (lot) do nothing;
`

writeFileSync(new URL('../db/seed_machines.sql', import.meta.url), sql)
console.log(`wrote ${machines.length} machines`)
