import type { Machine } from './types'

export const EVENT = {
  name: 'Ritchie Bros. Netherlands Unreserved Auction',
  venue: 'Zevenbergen / Port of Moerdijk, Netherlands',
  address: 'Mark S Clarkelaan 21, Haven M530, 4761 RK Zevenbergen, Netherlands',
  viewing: 'Mon 7 Sep & Tue 8 Sep 2026 · 08:00–16:00',
  accessLotsClose: 'Wed 9 Sep 2026 · access block starts around 14:28 local venue time',
  telehandlerLotsClose: 'Wed 9 Sep 2026 · first block starts 08:30 local venue time',
  paymentDue: 'Thu 17 Sep 2026',
  removalDue: 'Thu 24 Sep 2026',
  mode: 'Timed online auction — no live auctioneer',
  catalogUrl: 'https://www.rbauction.com/heavy-equipment-auctions/zevenbergen-2026224',
}

export const CATEGORY_COUNTS = [
  { label: 'Scissor lifts', count: 150 },
  { label: 'Articulating booms', count: 82 },
  { label: 'Vertical mast lifts', count: 80 },
  { label: 'Telescopic booms', count: 36 },
  { label: 'Telehandlers', count: 25 },
]

export const machines: Machine[] = [
  {
    lot: 659, year: 2013, make: 'JLG', model: '800AJ',
    title: '2013 JLG 800AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 4549, serial: '0300169353',
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/238/e4228d04-ec58-4647-a53e-edb96357b379-med.jpg',
    sourceUrl: 'https://www.rbauction.co.uk/pdp/2013-jlg-800aj-4wd-diesel-articulating-boom-lift/15767810',
    features: ['24.38 m max platform height', '230 kg platform capacity', 'Jib', 'Deutz 4-cylinder diesel'],
    notes: 'Catalog deficiency note: unusual sound from drivetrain. Treat as a red-flag inspection item.',
    sourceVerified: true,
  },
  {
    lot: 667, year: 2015, make: 'JLG', model: '600AJ',
    title: '2015 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3594, serial: '0300199652',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/233/3eec8e9b-6835-42ec-b845-723767816798-med.jpg',
    sourceUrl: 'https://www.rbauction.co.uk/pdp/2015-jlg-600aj-4wd-diesel-articulating-boom-lift/15767805',
    features: ['18.29 m max platform height', '230 kg platform capacity', 'Jib', 'Power to platform', 'Deutz 4-cylinder diesel'],
    notes: 'Tied closing group with Lot 666.',
    sourceVerified: true,
  },
  {
    lot: 690, year: 2017, make: 'Haulotte', model: 'HA18SPX',
    title: '2017 Haulotte HA18SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3827,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/242/fdae8ef1-110f-4216-aad9-446c9ea0a14e-med.jpg',
    sourceUrl: 'https://www.rbauction.co.uk/pdp/2017-haulotte-ha18spx-4wd-diesel-articulating-boom-lift/15767814',
    features: ['4WD diesel articulated boom', 'Approx. EHS core 16–20 m rental class'],
    sourceVerified: true,
  },
  {
    lot: 834, year: 2015, make: 'Haulotte', model: 'H18SXL',
    title: '2015 Haulotte H18SXL 4x4 Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 589, serial: 'CD118250',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22702/798/00d22c30-e9ad-4fb5-aa47-80e4a291d92f-med.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2015-haulotte-h18sxl-4x4-diesel-scissor-lift/15724530',
    features: ['16 m max platform height', '500 kg platform capacity', 'Platform extension', 'Stabilizers', 'Hatz 2-cylinder diesel'],
    sourceVerified: true,
  },
  {
    lot: 873, year: 2016, make: 'Haulotte', model: 'Compact 12',
    title: '2016 Haulotte COMPACT 12 Electric Scissor Lift',
    category: 'Scissor Lift', power: 'Electric', hours: 302, serial: '2010613',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22920/408/573caa77-9ba0-4931-bc9a-52d751dcef9a-med.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2016-haulotte-compact-12-electric-scissor-lift/15838025',
    features: ['9.75 m max platform height', '300 kg platform capacity', 'Platform extension', 'Power to platform', 'Solid non-marking tyres'],
    notes: 'Tied closing group with Lot 872.',
    sourceVerified: true,
  },
  {
    lot: 758, year: 2021, make: 'ATN', model: 'PIAF 10RE',
    title: '2021 ATN PIAF 10RE Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 137, serial: 'P1021023',
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/261/bd430a40-b465-47b0-a299-ec87d8a40028-med.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2021-atn-piaf-10re-vertical-mast-lift/15767831',
    features: ['8 m max platform height', '200 kg platform capacity', 'Upper control box'],
    notes: 'Tied closing group with Lot 759.',
    sourceVerified: true,
  },
  {
    lot: 763, year: 2016, make: 'Genie', model: 'GR-20',
    title: '2016 Genie GR-20 Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 172, serial: 'GR16P43741',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22860/681/4fec55ba-bb15-46f3-80f8-4ea76b2070c9-med.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2016-genie-gr-20-vertical-mast-lift/15800316',
    features: ['6 m max platform height', '159 kg platform capacity', 'Platform extension', 'Power to platform', 'Solid non-marking tyres'],
    notes: 'Tied closing group with Lots 762–767.',
    sourceVerified: true,
  },
  {
    lot: 100, year: 2023, make: 'Bobcat', model: 'T40.180SLPRC',
    title: '2023 Bobcat T40.180SLPRC Telehandler',
    category: 'Telehandler', power: 'Diesel', hours: 2081, serial: 'B54V11307',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 4, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22849/2/b615f060-13dc-41ca-812d-953ac48afa96-med.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2023-bobcat-t40.180slprc-telehandler/15792601',
    features: ['14 m max lift height', '3000 kg max lift capacity', 'Enclosed cab + AC', 'Load moment indicator', 'Hydraulic coupler', 'Outriggers'],
    notes: 'Catalog note says no registration available; digital CE copy available.',
    sourceVerified: true,
  },
  {
    lot: 107, year: 2018, make: 'Manitou', model: 'MHT790',
    title: '2018 Manitou MHT790 Telehandler',
    category: 'Telehandler', power: 'Diesel', hours: 2555, serial: 'MAN00000E00774275',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22809/940/4e05c3ed-08f7-4cb4-956a-be5a0d8f0ae3-med.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2018-manitou-mht790-telehandler/15760120',
    features: ['7 m max lift height', '9000 kg max lift capacity', 'Enclosed cab + AC', 'Load moment indicator', 'Fork positioner', 'Auxiliary hydraulics'],
    notes: 'Dutch registration available; first registered June 2018.',
    sourceVerified: true,
  },
  {
    lot: 95, year: 2014, make: 'Manitou', model: 'MRT2150+',
    title: '2014 Manitou MRT2150+ Telehandler',
    category: 'Telehandler', power: 'Diesel', hours: 5058, serial: '766437',
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22835/435/3cba7bf0-b1ea-4096-aab8-350c6cb3c4df-small.jpg',
    sourceUrl: 'https://www.rbauction.com/pdp/2014-manitou-mrt2150-telehandler/15783459',
    features: ['21 m max lift height', '4999 kg max lift capacity', 'Air ride seat', 'Load moment indicator', 'Outriggers', 'Auxiliary hydraulics'],
    notes: 'Catalog note says no registration available; copy of CE certificate available.',
    sourceVerified: true,
  }
]

export const INSPECTION_SECTIONS = [
  ['Structure & chassis', 'Cracks, weld repairs, boom/scissor arms, chassis distortion, turntable play'],
  ['Hydraulics', 'Cylinders, rods, seals, hoses, leaks, drift, pump noise and pressure response'],
  ['Engine / battery', 'Cold start, smoke/blow-by or battery pack condition, charger and cables'],
  ['Drivetrain & brakes', 'Drive motors/axles, hub noise, steering, braking, oscillating axle'],
  ['Controls & electronics', 'Ground/platform controls, CAN faults, displays, sensors, E-stops'],
  ['Lift functions', 'Full extension/elevation, slew, jib, platform rotate, leveling, emergency lowering'],
  ['Tyres / wheels', 'Tyre type, wear, cuts, foam fill, non-marking condition, wheel damage'],
  ['Safety systems', 'Tilt alarm, overload, interlocks, pothole protection, emergency descent'],
  ['Documentation', 'Serial/VIN, CE, manuals, hour meter, registration, service records'],
  ['Overall rental readiness', 'Clean-up, predictable repair scope, parts availability, customer acceptance'],
] as const

export const CRITICAL_CHECKS = [
  'No structural crack or unsafe weld repair',
  'Emergency lowering works',
  'E-stop and safety interlocks work',
  'No major hydraulic leak',
  'Serial / identity plate matches catalog',
  'Controls operate without critical fault',
]
