import type { Machine } from './types'

export const EVENT = {
  name: 'Ritchie Bros. Netherlands Unreserved Auction',
  venue: 'Zevenbergen / Port of Moerdijk, Netherlands',
  address: 'Mark S Clarkelaan 21, Haven M530, 4761 RK Zevenbergen, Netherlands',
  viewing: 'Mon 7 Sep & Tue 8 Sep 2026 · 08:00–16:00',
  accessLotsClose: 'Wed 9 Sep 2026 · access block starts around 14:28 local venue time',
  telehandlerLotsClose: 'Wed 9 Sep 2026 · first block starts 08:30 local venue time',
  paymentDue: 'Thu 17 Sep 2026',
  removalDue: 'Thu 24 Sep 2026',
  mode: 'Timed online auction — no live auctioneer',
  catalogUrl: 'https://www.rbauction.com/heavy-equipment-auctions/zevenbergen-2026224',
}

export const CATEGORY_COUNTS = [
  { label: 'Scissor lifts', count: 150 },
  { label: 'Articulating booms', count: 82 },
  { label: 'Vertical mast lifts', count: 80 },
  { label: 'Telescopic booms', count: 36 },
  { label: 'Telehandlers', count: 25 },
]

export const machines: Machine[] = [
  {
    lot: 630, year: 2008, make: 'Haulotte', model: 'H23TPX',
    title: '2008 Haulotte H23TPX 4WD Diesel Telescopic Boom Lift',
    category: 'Telescopic Boom Lift', power: 'Diesel', hours: 7581,
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=H23TPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 631, year: 2014, make: 'Haulotte', model: 'HT23RTJ',
    title: '2014 Haulotte HT23RTJ 4WD Diesel Telescopic Boom Lift',
    category: 'Telescopic Boom Lift', power: 'Diesel', hours: 4984,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HT23RTJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 655, year: 2010, make: 'Genie', model: 'Z-135',
    title: '2010 Genie Z-135 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 6125,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=Z-135',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 656, year: 2008, make: 'Genie', model: 'Z-135',
    title: '2008 Genie Z-135 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 7783,
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=Z-135',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 657, year: 2008, make: 'Haulotte', model: 'HA41PX',
    title: '2008 Haulotte HA41PX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 7395,
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA41PX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 659, year: 2013, make: 'JLG', model: '800AJ',
    title: '2013 JLG 800AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 4549,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/238/e4228d04-ec58-4647-a53e-edb96357b379-med.jpg',
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=800AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 665, year: 2015, make: 'Haulotte', model: 'HA20PX',
    title: '2015 Haulotte HA20PX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3058,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA20PX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 666, year: 2015, make: 'JLG', model: '600AJ',
    title: '2015 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3256,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 667, year: 2015, make: 'JLG', model: '600AJ',
    title: '2015 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3594,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/233/3eec8e9b-6835-42ec-b845-723767816798-med.jpg',
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 668, year: 2015, make: 'JLG', model: '600AJ',
    title: '2015 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 4183,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 669, year: 2014, make: 'JLG', model: '600AJ',
    title: '2014 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 2961,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 670, year: 2014, make: 'JLG', model: '600AJ',
    title: '2014 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3890,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 671, year: 2014, make: 'JLG', model: '600AJ',
    title: '2014 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3999,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 672, year: 2011, make: 'JLG', model: '600AJ',
    title: '2011 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 4212,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 673, year: 2010, make: 'JLG', model: '600AJ',
    title: '2010 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3635,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 674, year: 2015, make: 'JLG', model: '600AJ',
    title: '2015 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 1628,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 675, year: 2015, make: 'JLG', model: '600AJ',
    title: '2015 JLG 600AJ 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 2249,
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 3, partsSupport: 5, rentalDemand: 3,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=600AJ',
    features: [],
    notes: 'CATALOG FLAGS THIS LOT AS INOPERABLE. Verify what is wrong before bidding - it may be a battery or a controller, or it may be the boom.',
    sourceVerified: true,
  },
  {
    lot: 676, year: 2010, make: 'JLG', model: 'E600JP',
    title: '2010 JLG E600JP Electric Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Electric', hours: 1366,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 5,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=E600JP',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 690, year: 2017, make: 'Haulotte', model: 'HA18SPX',
    title: '2017 Haulotte HA18SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 3827,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    imageUrl: 'https://www-ironplanet.s3-us-west-2.amazonaws.com/i/22819/242/fdae8ef1-110f-4216-aad9-446c9ea0a14e-med.jpg',
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA18SPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 691, year: 2013, make: 'Haulotte', model: 'HA18SPX',
    title: '2013 Haulotte HA18SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 5345,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA18SPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 692, year: 2007, make: 'Haulotte', model: 'HA18SPX',
    title: '2007 Haulotte HA18SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 7567,
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA18SPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 693, year: 2014, make: 'Haulotte', model: 'HA16PX',
    title: '2014 Haulotte HA16PX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel',
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA16PX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 694, year: 2013, make: 'Haulotte', model: 'HA16SPX',
    title: '2013 Haulotte HA16SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel',
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 3, partsSupport: 5, rentalDemand: 2,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA16SPX',
    features: [],
    notes: 'CATALOG FLAGS THIS LOT AS INOPERABLE. Verify what is wrong before bidding - it may be a battery or a controller, or it may be the boom.',
    sourceVerified: true,
  },
  {
    lot: 695, year: 2012, make: 'Haulotte', model: 'HA16SPX',
    title: '2012 Haulotte HA16SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 5013,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA16SPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 696, year: 2011, make: 'Haulotte', model: 'HA16SPX',
    title: '2011 Haulotte HA16SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel',
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 3, partsSupport: 5, rentalDemand: 2,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA16SPX',
    features: [],
    notes: 'CATALOG FLAGS THIS LOT AS INOPERABLE. Verify what is wrong before bidding - it may be a battery or a controller, or it may be the boom.',
    sourceVerified: true,
  },
  {
    lot: 697, year: 2006, make: 'Haulotte', model: 'HA16SPX',
    title: '2006 Haulotte HA16SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 8860,
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA16SPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 698, year: 2011, make: 'Haulotte', model: 'HA16SPX',
    title: '2011 Haulotte HA16SPX 4WD Diesel Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Diesel', hours: 4811,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA16SPX',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 728, year: 2017, make: 'Haulotte', model: 'HA15IP',
    title: '2017 Haulotte HA15IP Electric Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Electric', hours: 3920,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA15IP',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 729, year: 2014, make: 'Haulotte', model: 'HA12IP',
    title: '2014 Haulotte HA12IP Electric Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Electric', hours: 474,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA12IP',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 730, year: 2012, make: 'Haulotte', model: 'HA12IP',
    title: '2012 Haulotte HA12IP Electric Articulating Boom Lift',
    category: 'Articulating Boom Lift', power: 'Electric', hours: 511,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=HA12IP',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 744, year: 2022, make: 'Haulotte', model: 'STAR 10 AE',
    title: '2022 Haulotte STAR 10 AE Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 980,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010%20AE',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 745, year: 2018, make: 'Haulotte', model: 'STAR 10',
    title: '2018 Haulotte STAR 10 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 325,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 746, year: 2016, make: 'Haulotte', model: 'STAR10',
    title: '2016 Haulotte STAR10 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric',
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 3, partsSupport: 5, rentalDemand: 2,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR10',
    features: [],
    notes: 'CATALOG FLAGS THIS LOT AS INOPERABLE. Verify what is wrong before bidding - it may be a battery or a controller, or it may be the boom.',
    sourceVerified: true,
  },
  {
    lot: 747, year: 2016, make: 'Haulotte', model: 'STAR 10',
    title: '2016 Haulotte STAR 10 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 105,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 748, year: 2015, make: 'Haulotte', model: 'STAR 10-1',
    title: '2015 Haulotte STAR 10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 454,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 751, year: 2014, make: 'Haulotte', model: 'STAR10-1',
    title: '2014 Haulotte STAR10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 737,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR10-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 752, year: 2014, make: 'Haulotte', model: 'STAR10',
    title: '2014 Haulotte STAR10 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric',
    location: 'Zevenbergen, Netherlands', priority: 'P3', fleetFit: 3, partsSupport: 5, rentalDemand: 2,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR10',
    features: [],
    notes: 'CATALOG FLAGS THIS LOT AS INOPERABLE. Verify what is wrong before bidding - it may be a battery or a controller, or it may be the boom.',
    sourceVerified: true,
  },
  {
    lot: 753, year: 2011, make: 'Haulotte', model: 'STAR 10-1',
    title: '2011 Haulotte STAR 10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 55,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 754, year: 2010, make: 'Haulotte', model: 'STAR 10-1',
    title: '2010 Haulotte STAR 10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric',
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 755, year: 2010, make: 'Haulotte', model: 'STAR 10-1',
    title: '2010 Haulotte STAR 10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 452,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 756, year: 2009, make: 'Haulotte', model: 'STAR 10-1',
    title: '2009 Haulotte STAR 10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric',
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 757, year: 2014, make: 'Haulotte', model: 'STAR 10-1',
    title: '2014 Haulotte STAR 10-1 Electric Vertical Mast Lift',
    category: 'Vertical Mast Lift', power: 'Electric', hours: 96,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 5, partsSupport: 5, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=STAR%2010-1',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 824, year: 2015, make: 'Genie', model: 'GS-5390',
    title: '2015 Genie GS-5390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 1926,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS-5390',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 825, year: 2014, make: 'Genie', model: 'GS-5390',
    title: '2014 Genie GS-5390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 1607,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS-5390',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 826, year: 2014, make: 'Genie', model: 'GS-5390',
    title: '2014 Genie GS-5390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 2055,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS-5390',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 827, year: 2014, make: 'Genie', model: 'GS-5390',
    title: '2014 Genie GS-5390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 2119,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS-5390',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 828, year: 2014, make: 'Genie', model: 'GS-5390',
    title: '2014 Genie GS-5390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 2525,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS-5390',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 829, year: 2011, make: 'Genie', model: 'GS-5390',
    title: '2011 Genie GS-5390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 4028,
    location: 'Zevenbergen, Netherlands', priority: 'P2', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS-5390',
    features: [],
    sourceVerified: true,
  },
  {
    lot: 844, year: 2016, make: 'Genie', model: 'GS3390',
    title: '2016 Genie GS3390 4WD Diesel Scissor Lift',
    category: 'Scissor Lift', power: 'Diesel', hours: 1536,
    location: 'Zevenbergen, Netherlands', priority: 'P1', fleetFit: 4, partsSupport: 3, rentalDemand: 4,
    sourceUrl: 'https://www.rbauction.co.uk/heavy-equipment-auctions/zevenbergen-nld-2026224?freeText=GS3390',
    features: [],
    sourceVerified: true,
  },
]

export const INSPECTION_SECTIONS = [
  ['Structure & chassis', 'Cracks, weld repairs, boom/scissor arms, chassis distortion, turntable play'],
  ['Hydraulics', 'Cylinders, rods, seals, hoses, leaks, drift, pump noise and pressure response'],
  ['Engine / battery', 'Cold start, smoke/blow-by or battery pack condition, charger and cables'],
  ['Drivetrain & brakes', 'Drive motors/axles, hub noise, steering, braking, oscillating axle'],
  ['Controls & electronics', 'Ground/platform controls, CAN faults, displays, sensors, E-stops'],
  ['Lift functions', 'Full extension/elevation, slew, jib, platform rotate, leveling, emergency lowering'],
  ['Tyres / wheels', 'Tyre type, wear, cuts, foam fill, non-marking condition, wheel damage'],
  ['Safety systems', 'Tilt alarm, overload, interlocks, pothole protection, emergency descent'],
  ['Documentation', 'Serial/VIN, CE, manuals, hour meter, registration, service records'],
  ['Overall rental readiness', 'Clean-up, predictable repair scope, parts availability, customer acceptance'],
] as const

export const CRITICAL_CHECKS = [
  'No structural crack or unsafe weld repair',
  'Emergency lowering works',
  'E-stop and safety interlocks work',
  'No major hydraulic leak',
  'Serial / identity plate matches catalog',
  'Controls operate without critical fault',
]
